# Generated by Django 3.1.1 on 2020-10-06 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Undefined', max_length=64)),
                ('description', models.TextField(default='No description.')),
                ('createdAt', models.DateTimeField(default=0)),
                ('deadline', models.DateField(null=True)),
                ('status', models.TextField(choices=[('New', 'New'), ('Planned', 'Planned'), ('In progress', 'In Progress'), ('Completed', 'Completed')], default='New')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLogTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('changeTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('data', models.JSONField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
    ]
