# Generated by Django 3.1.1 on 2020-10-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201007_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changelogtask',
            old_name='changeTime',
            new_name='change_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
